package com.owasp.lab.controller;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.io.*;
import java.util.Base64;

/**
 * Insecure deserialisation demo.
 *
 * VULNERABILITY (OWASP A08:2021 - Software and Data Integrity Failures):
 *
 * This endpoint accepts a base64-encoded serialized Java object in the
 * request body and deserialises it using {@link ObjectInputStream} without
 * any filtering.  Java native deserialisation can lead to Remote Code
 * Execution via gadget chains (commons-collections, spring-core, etc.).
 *
 * Try with a malicious payload generated by ysoserial:
 *   java -jar ysoserial.jar CommonsCollections6 "calc.exe" | base64
 *
 * DO NOT expose this on any network.
 */
@RestController
@RequestMapping("/api/deserialize")
public class InsecureDeserializationController {

    @PostMapping(consumes = MediaType.TEXT_PLAIN_VALUE)
    public ResponseEntity<?> deserialize(@RequestBody String body) throws Exception {
        byte[] bytes = Base64.getDecoder().decode(body);
        // VULNERABILITY: unsafe native Java deserialisation
        try (ObjectInputStream ois = new ObjectInputStream(new ByteArrayInputStream(bytes))) {
            Object o = ois.readObject();
            return ResponseEntity.ok("Deserialized: " + o.getClass().getName());
        }
    }
}
